### ISSUE TITLE
'invalid argument' after cam.startrecord()

### ISSUE THREAD

**Issue by petaflot** [TinkerTurtle/Sentry-Picam#1]
after typing

cam.startrecord()

in the javascript console, 

I get no video record ; instead a lot of lines like
2020/08/22 14:46:58 Message Received: startrecord
2020/08/22 14:47:11 invalid argument
2020/08/22 14:47:11 invalid argument
...
2020/08/22 14:47:19 invalid argument
2020/08/22 14:47:20 invalid argument
2020/08/22 14:47:20 invalid argument
2020/08/22 14:47:20 invalid argument
2020/08/22 14:47:20 invalid argument
2020/08/22 14:47:20 Message Received: stoprecord

in the bash console of simple-webcam. the messages are triggered at the first motion detected after startrecord until a stoprecord is received.

as as side note, I have a few more errors and warnings on Brave as well as no video display (only the motion detection squares), not sure if this is related. Attaching a screenshot for reference: https://www.imgpaste.net/image/9SGNa

**Comment by TinkerTurtle** [comment]
The lack of video is likely related to the errors in the browser, and the problem is probably with the video stream. Since you're seeing the motion detection squares, I'm guessing you might not be using Camera Module v2? or there's something unknown that's interfering with the video stream -- maybe a network port conflict? This uses [ports 8081 and 8082](https://github.com/TinkerTurtle/simple-webcam/blob/master/main.go#L275) to copy video from raspivid.

If other camera modules are used, the config might need to be changed here: https://github.com/TinkerTurtle/simple-webcam/blob/master/pkg/raspivid/raspivid.go#L28

**Comment by frrik** [comment]
the "invalid argument" happens if the video output directory "www/recordings" does not exist, which it won't after cloning the repository.

**Comment by TinkerTurtle** [comment]
@frrik Thanks for figuring this out. Ideally the program would create the folder if it doesn't exist, but I've added it to the repository in the meantime.
