### ISSUE TITLE
raspivid has been replaced by libcamera in raspbian bullseye

### ISSUE THREAD

**Issue by flbla** [TinkerTurtle/Sentry-Picam#3]
Hello,
raspivid has been replaced by libcamera in raspbian bullseye :
https://www.raspberrypi.com/news/raspberry-pi-os-debian-bullseye/

**Comment by TinkerTurtle** [comment]
I tried making a prototype on bullseye but unfortunately libcamera does not have access to motion vectors from the camera system. From this thread ( https://forums.raspberrypi.com/viewtopic.php?t=319116 ), it seems like it would require a lot of knowledge in order to provide this capability to libcamera.

I'm continuing to look for solutions for enabling efficient motion detection on Pi Zero.

**Comment by sordfish** [comment]
raspi-config has recently added legacy video support again. I've been using raspivid in bullseye no problem with another project.

**Comment by TinkerTurtle** [comment]
Closing due to available workaround, thanks @sordfish for the info

**Comment by Scrath1** [comment]
@sordfish Can you give an example on how to reenable raspivid?
I've enabled the "Legacy Camera" under Interface options in raspi-config and restartet the pi but I don't have the raspivid command available.

I'm on a Pi 4B Rev 1.4 if that matters.

**Comment by TinkerTurtle** [comment]
@Scrath1 You'll need the older version of Raspberry Pi OS labeled with "Debian version: 10 (buster)".
